name: gh-pages
on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - run: mkdir _site && cp index.html 404.html _site/
      - uses: actions/upload-pages-artifact@v4
        with:
          path: _site/
      - uses: actions/deploy-pages@v4
        id: deployment